# Generated by Django 4.1.7 on 2023-03-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_name', models.CharField(max_length=100)),
                ('ap_status', models.IntegerField()),
                ('edificio_id', models.IntegerField()),
                ('valor_aluguel', models.FloatField()),
                ('locatario_nome', models.CharField(max_length=100)),
                ('locatario_contato', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tblapartamento',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbledificio',
            },
        ),
    ]
