# Generated by Django 4.1.7 on 2023-03-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='locatario_contato',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='locatario_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='valor_aluguel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
