version: "3.3"
services:
  gestao:
    build:
      context: .
    container_name: gestao
    ports:
      - "8000:8000"
    depends_on:
      - database
  database:
    build:
      context: .
      dockerfile: Dokerfile
    ports:
      - "3306:3306"
    volumes:
      - ./:/docker-entrypoint-initdb.d/:ro
